---
version: '2.4'

services:
  deno:
    build:
      context: '.'
      dockerfile: 'Dockerfile'
      target: 'DEV'
    expose:
      - '8000'
    ports:
      - '8000:8000'
    volumes:
      - './backend:/app/backend'
    environment:
      - 'URI=www'

  www:
    build:
      context: '.'
      dockerfile: 'Dockerfile'
      target: 'FE_BUILD'
    command: 'npm start'
    expose:
      - '3000'
    ports:
      - '3000:3000'
    volumes:
      - './frontend:/app/frontend'
      - 'node_modules:/app/frontend/node_modules'
    environment:
      - 'REACT_APP_HOST=0.0.0.0'
    stdin_open: true

volumes:
  node_modules:
