name: Build Docker and Deploy to GCP

on:
  push:
    branches:
      - master

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup GCP
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Setup Node js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Auth docker
      run: gcloud auth configure-docker

    - name: Build App
      run: |
        cd ./frontend
        npm install
        npm run build

    - name: Build Docker
      run: |
        docker build --target PROD -t gcr.io/flock-community/flock-board:$GITHUB_SHA \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |
        docker push gcr.io/flock-community/flock-board:$GITHUB_SHA

    # Push the Docker image to Google Container Registry
    - name: Deploy
      run: |
        gcloud run deploy flock-board \
          --image=gcr.io/flock-community/flock-board:$GITHUB_SHA \
          --platform=managed \
          --region=europe-west4

